import type { Metadata } from "next";
import { Poiret_One} from 'next/font/google'
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";

const poiret = Poiret_One({subsets: ['latin'], weight: "400"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poiret.className} antialiased`}
      >
        <Navbar/>
        {children}
        {/* <Footer/> */}
      </body>
      
    </html>
  );
}
