import type { Metadata } from "next";
import { Jost } from 'next/font/google'
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";

const jost = Jost({subsets: ['latin'], weight: "400"});

export const metadata: Metadata = {
  title: "rethink*rotor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jost.className} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
      
    </html>
  );
}
